// SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note
/*
 * Copyright (c) 2024 AIROHA Inc
*/
#ifndef __UAPI_ECNT_EVENT_SERDES_SEL_H_
#define __UAPI_ECNT_EVENT_SERDES_SEL_H_

/************************************************************************
*               D E F I N E S   &   C O N S T A N T S
************************************************************************/

// #ifdef TCSUPPORT_BOARD_SELECT
// TODO: for AN7583 set as 1
#if 1

#ifndef DISABLE
#define DISABLE 0
#endif

#ifndef ENABLE
#define ENABLE 1
#endif

typedef enum ECNT_EVENT_SYSTEM_SERDES_PORT {
	ECNT_EVENT_SERDES_PORT_0 	= 0,
	ECNT_EVENT_SERDES_SEL_PON	= 0,	/* for 7523/7581/7552 */
	ECNT_EVENT_PON_HSGMII		= 0,	/* 7523 serdes IF 0 */
	ECNT_EVENT_SERDES_PORT_1	= 1,
	ECNT_EVENT_SERDES_SEL_ETHER = 1,	/* 7581 serdes IF 1 */
	ECNT_EVENT_USB3_HSGMII		= 1,	/* 7523 serdes IF 1 */
	ECNT_EVENT_SERDES_PORT_2	= 2,
	ECNT_EVENT_SERDES_SEL_WIFI1	= 2,	/* 7581 serdes IF 2 */
	ECNT_EVENT_PCIE0_HSGMII		= 2,	/* 7523 serdes IF 2 */
	ECNT_EVENT_SERDES_PORT_3	= 3,
	ECNT_EVENT_SERDES_SEL_WIFI2	= 3,	/* 7581 serdes IF 3 */
	ECNT_EVENT_PCIE1_HSGMII		= 3,	/* 7523 serdes IF 3 */
	ECNT_EVENT_SERDES_PORT_4	= 4,
	ECNT_EVENT_SERDES_SEL_USB1	= 4,	/* 7581 serdes IF 4 */
	ECNT_EVENT_SERDES_PORT_5	= 5,
	ECNT_EVENT_SERDES_SEL_USB2	= 5,	/* for 7581 */
	ECNT_EVENT_SERDES_PORT_6	= 6,
	ECNT_EVENT_SERDES_PORT_7	= 7,
	ECNT_EVENT_SERDES_PORT_8	= 8,
	ECNT_EVENT_SERDES_PORT_9	= 9,
} ECNT_EVENT_SYSTEM_SERDES_SEL_t;

/* SerDes I/F */
typedef enum ECNT_EVENT_SYSTEM_SERDES_IF{
	ECNT_EVENT_SERDES_PON_PON			= 0,	/* for 7523/7581/7552 */
	ECNT_EVENT_SERDES_ETHER_XFI			= 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_PCIE		= 0,	/* for 7523 */
	ECNT_EVENT_SERDES_WIFI2_PCIE		= 0,	/* for 7523 */
	ECNT_EVENT_SERDES_WIFI1_PCIE0_2LANE	= 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_PCIE0_2LANE = 0,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_USB30		= 0,	
	ECNT_EVENT_SERDES_USB2_USB30		= 0,	
	
	ECNT_EVENT_SERDES_PON_XFI			= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_ETHER_USXGMII		= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_PCIE0_1LANE	= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_PCIE1_1LANE	= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_HSGMII		= 1,	/* for 7523 */
	ECNT_EVENT_SERDES_USB2_PCIE2_1LANE	= 1,	/* for 7552 */
	
	ECNT_EVENT_SERDES_PON_USXGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_ETHER_HSGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_HSGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_HSGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_NONE			= 2,	/* for 7583 serdes-5 */
		
	ECNT_EVENT_SERDES_PON_HSGMII		= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_ETHER_5G_BASER	= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_USXGMII		= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_USXGMII		= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_SGMII		= 3,	/* for 7583 serdes-5 */
	
	ECNT_EVENT_SERDES_WIFI1_XFI			= 4,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_XFI			= 4,	/* for 7581 */
	
	ECNT_EVENT_SERDES_PON_NONE			= 4,	/* for 7583 serdes-1 */
	ECNT_EVENT_SERDES_ETHER_NONE		= 4,	/* for 7583 serdes-2 */
	ECNT_EVENT_SERDES_WIFI1_NONE		= 5,	/* for 7583 serdes-3 */
	ECNT_EVENT_SERDES_WIFI2_NONE		= 5,	/* for 7583 serdes-4 */
	ECNT_EVENT_SERDES_PON_SGMII			= 5,	/* for 7583 serdes-1 */
	
	ECNT_EVENT_SERDES_ETHER_FTTR_OLT	= 5,	/* for 7583 serdes-2 */
	ECNT_EVENT_SERDES_IF_PCIE_G3_1LANE	= 5,
	ECNT_EVENT_SERDES_IF_PCIE_G2_1LANE	= 6,
	ECNT_EVENT_SERDES_ETHER_SGMII		= 6,	/* for 7583 serdes-2 */
	ECNT_EVENT_SERDES_WIFI2_SGMII		= 6,	/* for 7583 serdes-4 */
	ECNT_EVENT_SERDES_IF_USB30			= 7,
	ECNT_EVENT_SERDES_IF_USB20_ONLY		= 8,
	ECNT_EVENT_SERDES_IF_USB20_HSGMII	= 9,
} ECNT_EVENT_SYSTEM_SERDES_IF_t;

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_ETHER_TYPE_NONE = 0,
	ECNT_EVENT_SERDES_ETHER_TYPE_LAN = 1,
	ECNT_EVENT_SERDES_ETHER_TYPE_WAN,
	ECNT_EVENT_SERDES_ETHER_TYPE_MAX,
	ECNT_EVENT_SERDES_ETHER_TYPE_ERROR = -1,
} ECNT_EVENT_SYSTEM_SERDES_ETHER_TYPE_SEL_t;

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_PHY_NONE = 0,
	ECNT_EVENT_SERDES_PHY_AN8811,
	ECNT_EVENT_SERDES_PHY_A,
	ECNT_EVENT_SERDES_PHY_B,
	ECNT_EVENT_SERDES_PHY_C,
	ECNT_EVENT_SERDES_PHY_D,
	ECNT_EVENT_SERDES_PHY_E,
	ECNT_EVENT_SERDES_PHY_DSL,
	ECNT_EVENT_SERDES_PHY_AN8831,
	ECNT_EVENT_SERDES_PHY_MAX,
	ECNT_EVENT_SERDES_PHY_ERROR = -1,
} ECNT_EVENT_SYSTEM_SERDES_PHY_SEL_t;

#else

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_ETHER_TYPE_NONE = 0,
	ECNT_EVENT_SERDES_ETHER_TYPE_LAN = 1,
	ECNT_EVENT_SERDES_ETHER_TYPE_WAN,
	ECNT_EVENT_SERDES_ETHER_TYPE_MAX,
} ECNT_EVENT_SYSTEM_SERDES_ETHER_TYPE_SEL_t;

/* SerDes-Port */
typedef enum {
// #ifdef TCSUPPORT_CPU_AN7552
// TODO: for AN7583 set as 0
#if 0
	ECNT_EVENT_SERDES_SEL_PON	= 0,	/* 7581 serdes IF 0 */
	ECNT_EVENT_SERDES_SEL_MAX,
	ECNT_EVENT_SERDES_SEL_WIFI1,
	ECNT_EVENT_SERDES_SEL_WIFI2,
	ECNT_EVENT_SERDES_SEL_ETHER,
#else
	ECNT_EVENT_SERDES_SEL_PON	= 0,	/* 7581 serdes IF 0 */
	ECNT_EVENT_PON_HSGMII		= 0,	/* 7523 serdes IF 0 */
	ECNT_EVENT_SERDES_SEL_ETHER = 1,	/* 7581 serdes IF 1 */
	ECNT_EVENT_USB3_HSGMII		= 1,	/* 7523 serdes IF 1 */
	ECNT_EVENT_SERDES_SEL_WIFI1 = 2,	/* 7581 serdes IF 2 */
	ECNT_EVENT_PCIE0_HSGMII		= 2,	/* 7523 serdes IF 2 */
	ECNT_EVENT_SERDES_SEL_WIFI2 = 3,	/* 7581 serdes IF 3 */
	ECNT_EVENT_PCIE1_HSGMII		= 3,	/* 7523 serdes IF 3 */
	ECNT_EVENT_SERDES_SEL_USB1,			/* 7581 serdes IF 4 */
	ECNT_EVENT_SERDES_SEL_USB2,			/* 7581 serdes IF 5 */
	ECNT_EVENT_SERDES_SEL_MAX,
#endif
}ECNT_EVENT_SYSTEM_SERDES_SEL_t;

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_PHY_NONE = 0,
	ECNT_EVENT_SERDES_PHY_AN8811,
	ECNT_EVENT_SERDES_PHY_A,
	ECNT_EVENT_SERDES_PHY_B,
	ECNT_EVENT_SERDES_PHY_C,
	ECNT_EVENT_SERDES_PHY_D,
	ECNT_EVENT_SERDES_PHY_E,
	ECNT_EVENT_SERDES_PHY_DSL,
	ECNT_EVENT_SERDES_PHY_AN8831,
	ECNT_EVENT_SERDES_PHY_MAX,
} ECNT_EVENT_SYSTEM_SERDES_PHY_SEL_t;

/* SerDes-PON */
typedef enum {
// #ifdef TCSUPPORT_CPU_AN7552
// TODO: for AN7583 set as 0
#if 0
	ECNT_EVENT_SERDES_PON_PON = 0,
	ECNT_EVENT_SERDES_PON_HSGMII,
	ECNT_EVENT_SERDES_PON_NONE,
	ECNT_EVENT_SERDES_PON_MAX,
	ECNT_EVENT_SERDES_PON_XFI,			/* for 7581 */
	ECNT_EVENT_SERDES_PON_USXGMII,
#else
	ECNT_EVENT_SERDES_PON_PON = 0,
	ECNT_EVENT_SERDES_PON_HSGMII,
	ECNT_EVENT_SERDES_PON_XFI,		/* for 7581 */
	ECNT_EVENT_SERDES_PON_USXGMII,
	ECNT_EVENT_SERDES_PON_NONE,		/* for 7581 */
	ECNT_EVENT_SERDES_PON_MAX,

#endif
	
}ECNT_EVENT_SYSTEM_SERDES_PON_SEL_t;

/* SerDes-Ethernet */
typedef enum {
	ECNT_EVENT_SERDES_ETHER_XFI = 0,
	ECNT_EVENT_SERDES_ETHER_USXGMII,
	ECNT_EVENT_SERDES_ETHER_HSGMII,
	ECNT_EVENT_SERDES_ETHER_5G_BASER,
	ECNT_EVENT_SERDES_ETHER_NONE,
	ECNT_EVENT_SERDES_ETHER_MAX,
}ECNT_EVENT_SYSTEM_SERDES_ETHER_SEL_t;

/* SerDes-WiFi1 */
typedef enum {
	ECNT_EVENT_SERDES_WIFI1_PCIE0_2LANE = 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_PCIE = 0,			/* for 7523 */
	ECNT_EVENT_SERDES_WIFI1_PCIE0_1LANE,		/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_HSGMII,
	ECNT_EVENT_SERDES_WIFI1_USXGMII,
	ECNT_EVENT_SERDES_WIFI1_XFI,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_NONE,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_MAX,
}ECNT_EVENT_SYSTEM_SERDES_WIFI1_SEL_t;

/* SerDes-WiFi2 */
typedef enum {
	ECNT_EVENT_SERDES_WIFI2_PCIE0_2LANE = 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_PCIE = 0,			/* for 7523 */
	ECNT_EVENT_SERDES_WIFI2_PCIE1_1LANE,		/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_HSGMII,
	ECNT_EVENT_SERDES_WIFI2_USXGMII,
	ECNT_EVENT_SERDES_WIFI2_XFI,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_NONE,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_MAX,
}ECNT_EVENT_SYSTEM_SERDES_WIFI2_SEL_t;

/* SerDes-USB1 */
typedef enum {
	ECNT_EVENT_SERDES_USB1_USB30 = 0,
	ECNT_EVENT_SERDES_USB1_HSGMII,
	ECNT_EVENT_SERDES_USB1_NONE,				/* for 7581 */
	ECNT_EVENT_SERDES_USB1_MAX,
}ECNT_EVENT_SYSTEM_SERDES_USB1_SEL_t;

 /* SerDes-USB2 */
typedef enum {
	ECNT_EVENT_SERDES_USB2_USB30 = 0,
	ECNT_EVENT_SERDES_USB2_PCIE2_1LANE,
	ECNT_EVENT_SERDES_USB2_NONE,
	ECNT_EVENT_SERDES_USB2_MAX,
}ECNT_EVENT_SYSTEM_SERDES_USB2_SEL_t;

#endif

#endif /* END OF __UAPI_ECNT_EVENT_SERDES_SEL_H_ */
